

#------------------------商品(目录)---------------------------
['商品']
menuId = 2000
icon = 'product'
path = 'pms'
    
#------------------------商品商品列表(二级菜单)---------------------------
['商品'.'商品列表']
menuId = 2001
icon = 'product-list'
path = 'product'

#-----------商品商品列表 按钮权限------------
['商品'.'商品列表'.'按钮权限'.'查询']
menuId = 2002
perms = 'query'

['商品'.'商品列表'.'按钮权限'.'添加']
menuId = 2003
perms = 'add'

['商品'.'商品列表'.'按钮权限'.'编辑']
menuId = 2004
perms = 'edit'

['商品'.'商品列表'.'按钮权限'.'删除']
menuId = 2005
perms = 'remove'

['商品'.'商品列表'.'按钮权限'.'导入']
menuId = 2006
perms = 'import'

['商品'.'商品列表'.'按钮权限'.'导出']
menuId = 2007
perms = 'export'

    
#------------------------商品添加商品(二级菜单)---------------------------
['商品'.'添加商品']
menuId = 2008
icon = 'product-add'
path = 'addProduct'

#-----------商品添加商品 按钮权限------------
['商品'.'添加商品'.'按钮权限'.'查询']
menuId = 2009
perms = 'query'

['商品'.'添加商品'.'按钮权限'.'添加']
menuId = 2010
perms = 'add'

['商品'.'添加商品'.'按钮权限'.'编辑']
menuId = 2011
perms = 'edit'

['商品'.'添加商品'.'按钮权限'.'删除']
menuId = 2012
perms = 'remove'

['商品'.'添加商品'.'按钮权限'.'导入']
menuId = 2013
perms = 'import'

['商品'.'添加商品'.'按钮权限'.'导出']
menuId = 2014
perms = 'export'

    
#------------------------商品商品分类(二级菜单)---------------------------
['商品'.'商品分类']
menuId = 2015
icon = 'product-cate'
path = 'productCate'

#-----------商品商品分类 按钮权限------------
['商品'.'商品分类'.'按钮权限'.'查询']
menuId = 2016
perms = 'query'

['商品'.'商品分类'.'按钮权限'.'添加']
menuId = 2017
perms = 'add'

['商品'.'商品分类'.'按钮权限'.'编辑']
menuId = 2018
perms = 'edit'

['商品'.'商品分类'.'按钮权限'.'删除']
menuId = 2019
perms = 'remove'

['商品'.'商品分类'.'按钮权限'.'导入']
menuId = 2020
perms = 'import'

['商品'.'商品分类'.'按钮权限'.'导出']
menuId = 2021
perms = 'export'

    
#------------------------商品商品类型(二级菜单)---------------------------
['商品'.'商品类型']
menuId = 2022
icon = 'product-attr'
path = 'productAttr'

#-----------商品商品类型 按钮权限------------
['商品'.'商品类型'.'按钮权限'.'查询']
menuId = 2023
perms = 'query'

['商品'.'商品类型'.'按钮权限'.'添加']
menuId = 2024
perms = 'add'

['商品'.'商品类型'.'按钮权限'.'编辑']
menuId = 2025
perms = 'edit'

['商品'.'商品类型'.'按钮权限'.'删除']
menuId = 2026
perms = 'remove'

['商品'.'商品类型'.'按钮权限'.'导入']
menuId = 2027
perms = 'import'

['商品'.'商品类型'.'按钮权限'.'导出']
menuId = 2028
perms = 'export'

    
#------------------------商品品牌管理(二级菜单)---------------------------
['商品'.'品牌管理']
menuId = 2029
icon = 'product-brand'
path = 'brand'

#-----------商品品牌管理 按钮权限------------
['商品'.'品牌管理'.'按钮权限'.'查询']
menuId = 2030
perms = 'query'

['商品'.'品牌管理'.'按钮权限'.'添加']
menuId = 2031
perms = 'add'

['商品'.'品牌管理'.'按钮权限'.'编辑']
menuId = 2032
perms = 'edit'

['商品'.'品牌管理'.'按钮权限'.'删除']
menuId = 2033
perms = 'remove'

['商品'.'品牌管理'.'按钮权限'.'导入']
menuId = 2034
perms = 'import'

['商品'.'品牌管理'.'按钮权限'.'导出']
menuId = 2035
perms = 'export'

    

#------------------------订单(目录)---------------------------
['订单']
menuId = 2036
icon = 'order'
path = 'oms'
    
#------------------------订单订单列表(二级菜单)---------------------------
['订单'.'订单列表']
menuId = 2037
icon = 'product-list'
path = 'order'

#-----------订单订单列表 按钮权限------------
['订单'.'订单列表'.'按钮权限'.'查询']
menuId = 2038
perms = 'query'

['订单'.'订单列表'.'按钮权限'.'添加']
menuId = 2039
perms = 'add'

['订单'.'订单列表'.'按钮权限'.'编辑']
menuId = 2040
perms = 'edit'

['订单'.'订单列表'.'按钮权限'.'删除']
menuId = 2041
perms = 'remove'

['订单'.'订单列表'.'按钮权限'.'导入']
menuId = 2042
perms = 'import'

['订单'.'订单列表'.'按钮权限'.'导出']
menuId = 2043
perms = 'export'

    
#------------------------订单订单设置(二级菜单)---------------------------
['订单'.'订单设置']
menuId = 2044
icon = 'order-setting'
path = 'orderSetting'

#-----------订单订单设置 按钮权限------------
['订单'.'订单设置'.'按钮权限'.'查询']
menuId = 2045
perms = 'query'

['订单'.'订单设置'.'按钮权限'.'添加']
menuId = 2046
perms = 'add'

['订单'.'订单设置'.'按钮权限'.'编辑']
menuId = 2047
perms = 'edit'

['订单'.'订单设置'.'按钮权限'.'删除']
menuId = 2048
perms = 'remove'

['订单'.'订单设置'.'按钮权限'.'导入']
menuId = 2049
perms = 'import'

['订单'.'订单设置'.'按钮权限'.'导出']
menuId = 2050
perms = 'export'

    
#------------------------订单退货申请处理(二级菜单)---------------------------
['订单'.'退货申请处理']
menuId = 2051
icon = 'order-return'
path = 'returnApply'

#-----------订单退货申请处理 按钮权限------------
['订单'.'退货申请处理'.'按钮权限'.'查询']
menuId = 2052
perms = 'query'

['订单'.'退货申请处理'.'按钮权限'.'添加']
menuId = 2053
perms = 'add'

['订单'.'退货申请处理'.'按钮权限'.'编辑']
menuId = 2054
perms = 'edit'

['订单'.'退货申请处理'.'按钮权限'.'删除']
menuId = 2055
perms = 'remove'

['订单'.'退货申请处理'.'按钮权限'.'导入']
menuId = 2056
perms = 'import'

['订单'.'退货申请处理'.'按钮权限'.'导出']
menuId = 2057
perms = 'export'

    
#------------------------订单退货原因设置(二级菜单)---------------------------
['订单'.'退货原因设置']
menuId = 2058
icon = 'order-return-reason'
path = 'returnReason'

#-----------订单退货原因设置 按钮权限------------
['订单'.'退货原因设置'.'按钮权限'.'查询']
menuId = 2059
perms = 'query'

['订单'.'退货原因设置'.'按钮权限'.'添加']
menuId = 2060
perms = 'add'

['订单'.'退货原因设置'.'按钮权限'.'编辑']
menuId = 2061
perms = 'edit'

['订单'.'退货原因设置'.'按钮权限'.'删除']
menuId = 2062
perms = 'remove'

['订单'.'退货原因设置'.'按钮权限'.'导入']
menuId = 2063
perms = 'import'

['订单'.'退货原因设置'.'按钮权限'.'导出']
menuId = 2064
perms = 'export'

    

#------------------------营销(目录)---------------------------
['营销']
menuId = 2065
icon = 'sms'
path = 'sms'
    
#------------------------营销秒杀活动列表(二级菜单)---------------------------
['营销'.'秒杀活动列表']
menuId = 2066
icon = 'sms-flash'
path = 'flash'

#-----------营销秒杀活动列表 按钮权限------------
['营销'.'秒杀活动列表'.'按钮权限'.'查询']
menuId = 2067
perms = 'query'

['营销'.'秒杀活动列表'.'按钮权限'.'添加']
menuId = 2068
perms = 'add'

['营销'.'秒杀活动列表'.'按钮权限'.'编辑']
menuId = 2069
perms = 'edit'

['营销'.'秒杀活动列表'.'按钮权限'.'删除']
menuId = 2070
perms = 'remove'

['营销'.'秒杀活动列表'.'按钮权限'.'导入']
menuId = 2071
perms = 'import'

['营销'.'秒杀活动列表'.'按钮权限'.'导出']
menuId = 2072
perms = 'export'

    
#------------------------营销优惠券列表(二级菜单)---------------------------
['营销'.'优惠券列表']
menuId = 2073
icon = 'sms-coupon'
path = 'coupon'

#-----------营销优惠券列表 按钮权限------------
['营销'.'优惠券列表'.'按钮权限'.'查询']
menuId = 2074
perms = 'query'

['营销'.'优惠券列表'.'按钮权限'.'添加']
menuId = 2075
perms = 'add'

['营销'.'优惠券列表'.'按钮权限'.'编辑']
menuId = 2076
perms = 'edit'

['营销'.'优惠券列表'.'按钮权限'.'删除']
menuId = 2077
perms = 'remove'

['营销'.'优惠券列表'.'按钮权限'.'导入']
menuId = 2078
perms = 'import'

['营销'.'优惠券列表'.'按钮权限'.'导出']
menuId = 2079
perms = 'export'

    
#------------------------营销品牌推荐(二级菜单)---------------------------
['营销'.'品牌推荐']
menuId = 2080
icon = 'product-brand'
path = 'homeBrand'

#-----------营销品牌推荐 按钮权限------------
['营销'.'品牌推荐'.'按钮权限'.'查询']
menuId = 2081
perms = 'query'

['营销'.'品牌推荐'.'按钮权限'.'添加']
menuId = 2082
perms = 'add'

['营销'.'品牌推荐'.'按钮权限'.'编辑']
menuId = 2083
perms = 'edit'

['营销'.'品牌推荐'.'按钮权限'.'删除']
menuId = 2084
perms = 'remove'

['营销'.'品牌推荐'.'按钮权限'.'导入']
menuId = 2085
perms = 'import'

['营销'.'品牌推荐'.'按钮权限'.'导出']
menuId = 2086
perms = 'export'

    
#------------------------营销新品推荐(二级菜单)---------------------------
['营销'.'新品推荐']
menuId = 2087
icon = 'sms-new'
path = 'homeNew'

#-----------营销新品推荐 按钮权限------------
['营销'.'新品推荐'.'按钮权限'.'查询']
menuId = 2088
perms = 'query'

['营销'.'新品推荐'.'按钮权限'.'添加']
menuId = 2089
perms = 'add'

['营销'.'新品推荐'.'按钮权限'.'编辑']
menuId = 2090
perms = 'edit'

['营销'.'新品推荐'.'按钮权限'.'删除']
menuId = 2091
perms = 'remove'

['营销'.'新品推荐'.'按钮权限'.'导入']
menuId = 2092
perms = 'import'

['营销'.'新品推荐'.'按钮权限'.'导出']
menuId = 2093
perms = 'export'

    
#------------------------营销人气推荐(二级菜单)---------------------------
['营销'.'人气推荐']
menuId = 2094
icon = 'sms-hot'
path = 'homeHot'

#-----------营销人气推荐 按钮权限------------
['营销'.'人气推荐'.'按钮权限'.'查询']
menuId = 2095
perms = 'query'

['营销'.'人气推荐'.'按钮权限'.'添加']
menuId = 2096
perms = 'add'

['营销'.'人气推荐'.'按钮权限'.'编辑']
menuId = 2097
perms = 'edit'

['营销'.'人气推荐'.'按钮权限'.'删除']
menuId = 2098
perms = 'remove'

['营销'.'人气推荐'.'按钮权限'.'导入']
menuId = 2099
perms = 'import'

['营销'.'人气推荐'.'按钮权限'.'导出']
menuId = 2100
perms = 'export'

    
#------------------------营销专题推荐(二级菜单)---------------------------
['营销'.'专题推荐']
menuId = 2101
icon = 'sms-subject'
path = 'homeSubject'

#-----------营销专题推荐 按钮权限------------
['营销'.'专题推荐'.'按钮权限'.'查询']
menuId = 2102
perms = 'query'

['营销'.'专题推荐'.'按钮权限'.'添加']
menuId = 2103
perms = 'add'

['营销'.'专题推荐'.'按钮权限'.'编辑']
menuId = 2104
perms = 'edit'

['营销'.'专题推荐'.'按钮权限'.'删除']
menuId = 2105
perms = 'remove'

['营销'.'专题推荐'.'按钮权限'.'导入']
menuId = 2106
perms = 'import'

['营销'.'专题推荐'.'按钮权限'.'导出']
menuId = 2107
perms = 'export'

    
#------------------------营销广告列表(二级菜单)---------------------------
['营销'.'广告列表']
menuId = 2108
icon = 'sms-ad'
path = 'homeAdvertise'

#-----------营销广告列表 按钮权限------------
['营销'.'广告列表'.'按钮权限'.'查询']
menuId = 2109
perms = 'query'

['营销'.'广告列表'.'按钮权限'.'添加']
menuId = 2110
perms = 'add'

['营销'.'广告列表'.'按钮权限'.'编辑']
menuId = 2111
perms = 'edit'

['营销'.'广告列表'.'按钮权限'.'删除']
menuId = 2112
perms = 'remove'

['营销'.'广告列表'.'按钮权限'.'导入']
menuId = 2113
perms = 'import'

['营销'.'广告列表'.'按钮权限'.'导出']
menuId = 2114
perms = 'export'

    